In [2]:

import pandas as pd
import numpy as np 


# Series 

In [3]:
#from ndarray
s=pd.Series(np.random.randn(5), index=['a', 'b', 'c', 'd', 'e'])
s

a    0.959447
b    1.516012
c    0.858753
d   -0.806542
e   -1.609498
dtype: float64

In [4]:
s.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [5]:
pd.Series(np.random.randn(5))

0   -1.145821
1    1.513898
2   -0.106275
3   -0.547164
4   -0.054932
dtype: float64

In [6]:
# from dictionary
d={'b':1, 'a':0,'c':2}
pd.Series(d)

b    1
a    0
c    2
dtype: int64

In [7]:
d={"a":0.0, "b":1.0, "c":2.0}
pd.Series(d)

a    0.0
b    1.0
c    2.0
dtype: float64

In [8]:
pd.Series(d, index=["b", "c", "d", "a"])


b    1.0
c    2.0
d    NaN
a    0.0
dtype: float64

In [9]:
#from scalar value
# fi the data is a scalar value, an index must be provided the value will be repeated to match the lenght of index
pd.Series(5.0, index=["a", "b", "c", "d", "e"])


a    5.0
b    5.0
c    5.0
d    5.0
e    5.0
dtype: float64

# series is ndarray like

In [10]:

#series acts very similarly to a ndarray and is a valid argument to most Numpy functions.
#however operations such as slicing will also slice the index

In [11]:
s=pd.Series(np.random.randn(5), index=["a", "b", "c" , "d", "e"])

s.iloc[0]


0.7070867240193318

In [12]:
s.iloc[:3]

a    0.707087
b   -1.217516
c   -0.236113
dtype: float64

In [13]:
s[s>s.median()]

a    0.707087
e   -0.046496
dtype: float64

In [14]:
s.iloc[[4,3,1]]

e   -0.046496
d   -0.489112
b   -1.217516
dtype: float64

In [15]:
np.exp(s)

a    2.028074
b    0.295964
c    0.789692
d    0.613170
e    0.954569
dtype: float64

In [16]:
s=pd.Series(np.random.randn(5), index=["a", "b", "c", "d", "e"])
subset_positional=s[1:3]

print("Original Series")
print(s)

print("Subset(Postional Indexing):")
print(subset_positional)



Original Series
a   -0.392349
b   -1.244292
c   -0.665327
d    0.253693
e   -0.400082
dtype: float64
Subset(Postional Indexing):
b   -1.244292
c   -0.665327
dtype: float64


In [17]:
print(s["b"])
print(subset_positional["b"])

-1.2442916454012167
-1.2442916454012167


In [18]:
print(s[0])
print(subset_positional[0])

-0.3923486636024642
-1.2442916454012167


C:\Users\aadit\AppData\Local\Temp\ipykernel_18200\1918086105.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[0])
C:\Users\aadit\AppData\Local\Temp\ipykernel_18200\1918086105.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(subset_positional[0])


##### we can provide the labeled index to the series but not the numpy array. thus when we do the slicing of the series the labeled index get sliced as well. 


##### when we do the slicing of the series or a array the subset is the view of the orginal series or the array. thus wnen we do the modification of the subset the original series or original array also get modified

In [19]:
#Series slicing with shared data

import pandas as pd
import numpy as np

s=pd.Series(np.random.randn(5))

subset=s[1:3]

print("Original Series")
print(s)

print("\nSubset:")
print(subset)

#modify the subset

subset[1]=99
print("\nModified Original series:")
print(s)
print("\nModified Subset")
print(subset)

Original Series
0    0.529036
1   -0.786069
2   -0.300621
3   -1.506446
4   -0.789676
dtype: float64

Subset:
1   -0.786069
2   -0.300621
dtype: float64

Modified Original series:
0     0.529036
1    99.000000
2    -0.300621
3    -1.506446
4    -0.789676
dtype: float64

Modified Subset
1    99.000000
2    -0.300621
dtype: float64


In [20]:
#array slicing with shared data
#modifying the values of a sliced NumPy array directly impacts the corresponding valuesin the original array
#since  the sliced array is a view into the underlying data

import numpy as np
arr=np.array([1,2,3,4,5])

subset=arr[1:4]

print("Original Array:")
print(arr)
print("\nSliced array:")
print(subset)

#modify the first element in the sliced array 
subset[0]=99

print("\nModified Original Array:")
print(arr)
print("\nModified Sliced Array:")
print(subset)

Original Array:
[1 2 3 4 5]

Sliced array:
[2 3 4]

Modified Original Array:
[ 1 99  3  4  5]

Modified Sliced Array:
[99  3  4]


In [21]:
#like NumPy array, a Pandas Series has a single dtype
s.dtype

dtype('float64')

In [22]:
#series to pandas array [extension array]
s.array
print(s.array.dtype)
print(type(s.array))

float64
<class 'pandas.core.arrays.numpy_.NumpyExtensionArray'>


In [23]:
# series to numpy ndarray
s.to_numpy()
print(s.to_numpy().dtype) #type of data inside the object 
print(type(s.to_numpy())) # type of the  object 

float64
<class 'numpy.ndarray'>


# series is dict-like

In [24]:
s["a"]

KeyError: 'a'

In [ ]:
s["e"]=12.0

In [ ]:
s

a    -0.547054
b     0.081320
c     0.759618
d     0.949790
e    12.000000
dtype: float64

In [ ]:
"e" in s

True

In [ ]:
"f" in s

False

In [ ]:
s.get("f")# no output since the f is not a label in the series s 

In [ ]:
s.get("f", np.nan) # returned specific default

nan

In [ ]:
#the labels can also be accessed by attribute
s.a

-0.5470541791242921

#### Different styles of accessing data in pandas series

In [ ]:
# all these are printing the data of label "a"
print(s["a"]) # dictionary-style access
print(s.a) #attribute style access
print(s.get("a")) #using get method
print(s.loc['a']) #label-based indexing
print(s.loc["a":"b"]) #label-based indexing 
print(s.iloc[0]) #integer - location based indexing
print(s.iloc[0:1]) #integer - location based indexing
print(s[0:1]) #slicing 
print(s[lambda x:x.index.isin(["a"])]) #callable function


-0.5470541791242921
-0.5470541791242921
-0.5470541791242921
-0.5470541791242921
a   -0.547054
b    0.081320
dtype: float64
-0.5470541791242921
a   -0.547054
dtype: float64
a   -0.547054
dtype: float64
a   -0.547054
dtype: float64


#### Vectorized operations and label alignment with Series 

In [ ]:
print(s)

a    -0.547054
b     0.081320
c     0.759618
d     0.949790
e    12.000000
dtype: float64


In [ ]:
s1=pd.Series(10, index=["a", "b", "c", "d", "e"])
s2=pd.Series(5, index=["a", "b", "d", "e"])

In [ ]:
print(s1)

a    10
b    10
c    10
d    10
e    10
dtype: int64


In [ ]:
print(s2)

a    5
b    5
d    5
e    5
dtype: int64


In [ ]:
print(s1+s2) #addition

a    15.0
b    15.0
c     NaN
d    15.0
e    15.0
dtype: float64


In [ ]:
s1-s2 #substraction 

a    5.0
b    5.0
c    NaN
d    5.0
e    5.0
dtype: float64

In [ ]:
s1*2 #multiplication 

a    20
b    20
c    20
d    20
e    20
dtype: int64

In [ ]:
s1/s2 #division 

a    2.0
b    2.0
c    NaN
d    2.0
e    2.0
dtype: float64

In [ ]:
s1//s2 #largest integer less than or equal to the result

a    2.0
b    2.0
c    NaN
d    2.0
e    2.0
dtype: float64

In [ ]:
s1**s2 #exponential (10 to the power 5)

a    100000.0
b    100000.0
c         NaN
d    100000.0
e    100000.0
dtype: float64

In [ ]:
s1%s2# modulus (remainders)

a    0.0
b    0.0
c    NaN
d    0.0
e    0.0
dtype: float64

In [ ]:
np.exp(s1)

a    22026.465795
b    22026.465795
c    22026.465795
d    22026.465795
e    22026.465795
dtype: float64

In [ ]:
#label alignment
s.iloc[1:]+s.iloc[:-1]

a         NaN
b    0.162640
c    1.519236
d    1.899579
e         NaN
dtype: float64

#### Name attribute

In [ ]:
s=pd.Series(np.random.randn(5), name="first series")
s

0   -0.455546
1   -0.403944
2   -0.598499
3    1.014273
4    1.322100
Name: first series, dtype: float64

In [ ]:
s=s.rename("final series")
s

0   -0.455546
1   -0.403944
2   -0.598499
3    1.014273
4    1.322100
Name: final series, dtype: float64

In [ ]:
pd.Series(
    data=np.random.randint(
        low=0, 
        high=16, 
        size=(4,1)
    ).flatten(),
    index=['a', 'b', 'c','d']
)

In [ ]:
pd.Series(
    np.diag(
        v=[1,2,3]
    ).flatten()
)

Revision

In [33]:
#different ways of creating Series
s1=pd.Series([1,2,3,4,5]) #from list
s2=pd.Series(np.random.randn(5)) #from random sample
s3=pd.Series(pd.Series(5, index=["a", "b", "c"])) #from scaler value with explicit index
s4=pd.Series(range(5)) #from range
s5=pd.Series(np.array([1,2,3,4,5]))#from numpy array
s6=pd.Series({'a':2, 'b':2, 'c':3}) #from dictionary



In [86]:
#different ways of creating arrays
a1=np.array([1,2,3,4,5]) #from  a provided values list
a2=np.random.randn(5) #random values array
a3=np.ones((5,)) #array of one
a4=np.zeros((5,)) #array of zeros
a5=np.arange(0,11,2) #(start, stop, step) 
a6=np.linspace(0,11,5) #(start, stop, number of points)
a7=np.empty(3) # create the random array from the values in its memory 
a8=np.eye(4) #identical matrix (0 and 1)
a9=np.diag([1,2,3]) #diagonal matrix
a10=np.array([[1,2,3], [4,5,6],[7,8,9]]) #from nested list
a11=np.random.randint(1,10, size=(3,3)) #random integer between 1 and 10, 3*3 array


In [ ]:
#np.zeros() # both for all
#np.ones()
#np.eye()
#np.diag()

#np.random.randn() #float values
#np.empty() #float values
#np.randint() #int values

#np.arange() both for all 
#np.linspace()

#np.array() #from list or nested list or tupple

