Pandas Data Types (dtypes):
1. int8, int16, int32, int64: Integer types with different bit sizes.
2. uint8, uint16, uint32, uint64: Unsigned integer types.
3. float16, float32, float64, float128: Floating-point types with different precision.
4. complex64, complex128, complex256: Complex number types.
5. bool: Boolean type.
6. object: Generic object type (can store any Python object).
7. datetime64[ns]: Datetime with nanosecond precision.
8. timedelta64[ns]: Timedeltas with nanosecond precision.
9. category: Categorical data type.
10. string: String data type (available in newer versions of Pandas).

In [3]:
import pandas as pd
import numpy as np

In [4]:
pd.date_range("1/1/2000", periods=8) # 8 days starting from first january 2000

DatetimeIndex(['2000-01-01', '2000-01-02', '2000-01-03', '2000-01-04',
               '2000-01-05', '2000-01-06', '2000-01-07', '2000-01-08'],
              dtype='datetime64[ns]', freq='D')

In [5]:
s=pd.Series(
    np.random.randn(5),
    index=["a","b","c","d","e"]
)
s

a   -0.762695
b   -0.768869
c   -0.412466
d    1.955028
e    0.706127
dtype: float64

In [6]:
df=pd.DataFrame(
    np.random.randn(8,3),
    index=pd.date_range("1/1/2000",periods=8),
    columns=["A","B","C"]
)

df

A         B         C
2000-01-01  2.463617 -0.556579 -0.611657
2000-01-02  0.516122 -0.794575 -0.637394
2000-01-03 -0.373286 -1.552922 -1.763501
2000-01-04 -0.497504 -0.186378  0.585913
2000-01-05 -0.212599  0.382449  1.448570
2000-01-06 -0.048921  1.312032  0.252213
2000-01-07 -1.359638  0.451464  2.262720
2000-01-08  0.192247 -2.241266 -1.103003

In [7]:
long_series=pd.Series(
    np.random.randn(1000)
)
print(long_series.head())
print(long_series.tail())

0    0.793494
1   -1.950357
2    1.355410
3   -0.789368
4    1.038090
dtype: float64
995    2.193938
996    0.345186
997   -1.479625
998   -0.195284
999    1.791463
dtype: float64


structure related attributes of the dataframe

In [8]:
df.shape #shape of the df

(8, 3)

In [9]:
df.index #index of  the columns

DatetimeIndex(['2000-01-01', '2000-01-02', '2000-01-03', '2000-01-04',
               '2000-01-05', '2000-01-06', '2000-01-07', '2000-01-08'],
              dtype='datetime64[ns]', freq='D')

In [10]:
df.columns #columns of the df

Index(['A', 'B', 'C'], dtype='object')

In [11]:
df.values #values of df 

array([[ 2.46361716, -0.55657921, -0.61165655],
       [ 0.51612154, -0.79457525, -0.63739433],
       [-0.3732858 , -1.55292179, -1.76350141],
       [-0.49750423, -0.18637797,  0.58591267],
       [-0.21259901,  0.38244866,  1.44857029],
       [-0.0489212 ,  1.31203192,  0.2522129 ],
       [-1.35963763,  0.4514645 ,  2.26272009],
       [ 0.19224743, -2.24126587, -1.10300258]])

In [12]:
df.axes #the index and columns of the dataframe

[DatetimeIndex(['2000-01-01', '2000-01-02', '2000-01-03', '2000-01-04',
                '2000-01-05', '2000-01-06', '2000-01-07', '2000-01-08'],
               dtype='datetime64[ns]', freq='D'),
 Index(['A', 'B', 'C'], dtype='object')]

In [13]:
df.ndim #dimension of the df = 2D

2

In [14]:
df.memory_usage()

Index    64
A        64
B        64
C        64
dtype: int64

In [15]:
df.size #total number of the values of  the dataframe

24

metadata related attributes

In [16]:
df.dtypes #datatype of each col

A    float64
B    float64
C    float64
dtype: object

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 8 entries, 2000-01-01 to 2000-01-08
Freq: D
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   A       8 non-null      float64
 1   B       8 non-null      float64
 2   C       8 non-null      float64
dtypes: float64(3)
memory usage: 256.0 bytes


In [18]:
df.describe() #stats of df

A         B         C
count  8.000000  8.000000  8.000000
mean   0.085005 -0.398222  0.054233
std    1.108281  1.147269  1.347409
min   -1.359638 -2.241266 -1.763501
25%   -0.404340 -0.984162 -0.753796
50%   -0.130760 -0.371479 -0.179722
75%    0.273216  0.399703  0.801577
max    2.463617  1.312032  2.262720

In [19]:
df.select_dtypes()#include, exlude

ValueError: at least one of include or exclude must be nonempty

In [ ]:
#to_numeric, pd.to_datetime, to_string(), to_timedelta()
df.convert_dtypes() #to change the datatype of the col in df

a         b         c
2000-01-01  1.157305  0.289316   0.34583
2000-01-02  1.157871 -0.754613  1.464736
2000-01-03  0.616951 -0.584048  1.745628
2000-01-04  0.783927  2.009028 -0.949201
2000-01-05  0.242035  0.857469  0.110306
2000-01-06  0.336588  0.075446 -0.469295
2000-01-07 -0.610323 -0.832809  1.759834
2000-01-08 -0.565661 -0.416436 -0.882457

content related attriutes of the dataframe

In [ ]:
df.values #all the values of df

array([[ 1.15730464,  0.28931553,  0.34583032],
       [ 1.1578708 , -0.75461304,  1.46473637],
       [ 0.61695071, -0.58404842,  1.7456277 ],
       [ 0.78392694,  2.00902761, -0.94920081],
       [ 0.2420348 ,  0.8574693 ,  0.11030587],
       [ 0.33658773,  0.07544647, -0.46929467],
       [-0.61032252, -0.83280899,  1.75983392],
       [-0.5656613 , -0.41643609, -0.88245743]])

In [ ]:
df.head(2) #first two records of the df 

a         b         c
2000-01-01  1.157305  0.289316  0.345830
2000-01-02  1.157871 -0.754613  1.464736

In [ ]:
df.tail(2) #last two records of df

a         b         c
2000-01-07 -0.610323 -0.832809  1.759834
2000-01-08 -0.565661 -0.416436 -0.882457

In [ ]:
df.sample(3) #get the random sample of 3 rows

a         b         c
2000-01-04  0.783927  2.009028 -0.949201
2000-01-05  0.242035  0.857469  0.110306
2000-01-02  1.157871 -0.754613  1.464736

In [ ]:
df.nunique() #return the total number of unique values in each column

a    8
b    8
c    8
dtype: int64

In [ ]:
df["a"].unique() #return the unique values of respective column

array([ 1.15730464,  1.1578708 ,  0.61695071,  0.78392694,  0.2420348 ,
        0.33658773, -0.61032252, -0.5656613 ])

In [ ]:
df.count() #returns the nun null values in each columns

a    8
b    8
c    8
dtype: int64

In [ ]:
df.mean() #compute the mean of each of the column of the df

a    0.389836
b    0.080419
c    0.390673
dtype: float64

In [ ]:
df.max() #compute the maximum value of each column

a    1.157871
b    2.009028
c    1.759834
dtype: float64

In [ ]:
df.median() #compute the median foe each column

a    0.476769
b   -0.170495
c    0.228068
dtype: float64

In [ ]:
df.min() #minimum value of each column

a   -0.610323
b   -0.832809
c   -0.949201
dtype: float64

In [ ]:
df.corr() #corelation of one numairc column to other 

a         b         c
a  1.000000  0.299568  0.091736
b  0.299568  1.000000 -0.674493
c  0.091736 -0.674493  1.000000

In [ ]:
df.sum() #sumof the values of each columns

a    3.118692
b    0.643352
c    3.125381
dtype: float64

In [ ]:
df.isnull()

a      b      c
2000-01-01  False  False  False
2000-01-02  False  False  False
2000-01-03  False  False  False
2000-01-04  False  False  False
2000-01-05  False  False  False
2000-01-06  False  False  False
2000-01-07  False  False  False
2000-01-08  False  False  False

In [ ]:
df.isnull().sum() #count of the total true values of each column i.e. total null values


a    0
b    0
c    0
dtype: int64

In [ ]:
df.notnull().sum()

a    8
b    8
c    8
dtype: int64

In [ ]:
df.duplicated().sum() #total number of duplicate record

1

pandas objects (Index, Series, DataFrame) can be thought of as containers for arrays, which hold the actual data and do the actual computation. For many types, the underlying array is a numpy.ndarray. However, pandas and 3rd party libraries may extend NumPy’s type system to add support for custom arrays (see dtypes).

In [ ]:
s.array

<NumpyExtensionArray>
[ -1.3285517156105917,  -0.8241506559866628,   -0.974499625369757,
  -1.2368136173314284, -0.10929247118816529]
Length: 5, dtype: float64

In [ ]:
s.index.array

<NumpyExtensionArray>
['a', 'b', 'c', 'd', 'e']
Length: 5, dtype: object

In [ ]:
#converting the series to the numpy array
s.to_numpy()
np.asarray(s)

array([-1.32855172, -0.82415066, -0.97449963, -1.23681362, -0.10929247])

In [ ]:
#tz="CET", timezone = central european time
# tz
#UTC = coordinated universal time
#GMT = Greenwich mean time
#US/Eastern= Eastern standard time
#US/Central =central standard time
#IST="Aisa/Kolkata" = Indian Standard Time
#Australia/Sydney = Australian Eastern Standard Time
#there are many other  timezones 

#'2000-01-01 00:00:00+1100'
# here it is showing 1 january 2000, midnight of australia, 
#Here, +1100 indicates the time offset from UTC (Universal Coordinated Time) for the CET time zone.

ser=pd.Series(pd.date_range("2000", periods=2, tz="Australia/Sydney"))
ser.to_numpy(dtype=object)




array([Timestamp('2000-01-01 00:00:00+1100', tz='Australia/Sydney'),
       Timestamp('2000-01-02 00:00:00+1100', tz='Australia/Sydney')],
      dtype=object)

datetime64[ns]

In [ ]:
# datetime format with nano seconds precision
ser=pd.Series(pd.date_range("2000", periods=2, tz="Australia/Sydney"))
ser.to_numpy(dtype="datetime64[ns]")
 #IT IS GIVING OUTPUT OF ARRAY WITH UTC TIMEZONE

array(['1999-12-31T13:00:00.000000000', '2000-01-01T13:00:00.000000000'],
      dtype='datetime64[ns]')

In [ ]:
import pandas as pd
import pytz
#this means the 2000-01-01 00:00:00+11:00 in Sydney
# Assuming ser is your Pandas DateTimeIndex with UTC time zone
ser = pd.to_datetime("1999-12-31T13:00:00.000000000", utc=True)
ser_sydney = ser.tz_convert('Australia/Sydney')

print(ser_sydney)


2000-01-01 00:00:00+11:00


timedelta64[ns]

In [ ]:
ser=pd.Series(pd.date_range("2000", periods=2, tz="Australia/Sydney"))
ser.to_numpy(dtype="timedelta64[ns]")

#946645200000000000 is the nanoseconds from reference time
#first january 1970 midnight 1970-01-01 00:00:00'

array([946645200000000000, 946731600000000000], dtype='timedelta64[ns]')

In [ ]:
from datetime import datetime, timedelta

# Convert nanoseconds to timedelta
duration = timedelta(seconds=946645200000000000 / 1e9)

# Add the duration to the Unix epoch
timestamp = datetime.utcfromtimestamp(0) + duration

print(timestamp)


1999-12-31 13:00:00


getting the underlying data from dataframe

In [ ]:
df

A         B         C
2000-01-01  0.291194 -0.547720  0.986394
2000-01-02  1.435346 -0.900886  0.145173
2000-01-03  0.418538 -0.830357  1.056603
2000-01-04  1.489134  1.522091  0.112341
2000-01-05  0.269677  0.863467  0.194527
2000-01-06  1.113750 -1.484883  0.910311
2000-01-07  1.130495 -0.129380 -0.214803
2000-01-08  0.083391 -0.454932  1.272007

In [ ]:
df.to_numpy()

array([[ 0.29119416, -0.54772001,  0.9863942 ],
       [ 1.4353455 , -0.90088628,  0.14517302],
       [ 0.41853772, -0.8303571 ,  1.05660279],
       [ 1.48913356,  1.5220906 ,  0.11234057],
       [ 0.26967714,  0.86346656,  0.19452681],
       [ 1.11375021, -1.48488347,  0.91031142],
       [ 1.13049471, -0.12938033, -0.21480349],
       [ 0.08339133, -0.45493222,  1.27200727]])

# Flexible binary operations
Binary operations and Reverse binary operations

In [ ]:
a=np.array(
    [
        [1,1,1],
        [2,2,2],
        [3,3,3],
        [4,4,4]
    ]
)

df=pd.DataFrame(
    a,
    columns=["A","B","C"]
)
df

A  B  C
0  1  1  1
1  2  2  2
2  3  3  3
3  4  4  4

In [ ]:
row=df.iloc[1,:]

In [ ]:
print(df.sub(row, axis=1))#df value - row value vertically 
print("=======") 
print(df.rsub(row, axis=1)) #row value - df value vertically

   A  B  C
0 -1 -1 -1
1  0  0  0
2  1  1  1
3  2  2  2
   A  B  C
0  1  1  1
1  0  0  0
2 -1 -1 -1
3 -2 -2 -2


In [ ]:
print(df.div(row, axis=1)) #df value/row value vertically 
print("==========")
print(df.rdiv(row, axis=1))#row value/df value vertically

     A    B    C
0  0.5  0.5  0.5
1  1.0  1.0  1.0
2  1.5  1.5  1.5
3  2.0  2.0  2.0
          A         B         C
0  2.000000  2.000000  2.000000
1  1.000000  1.000000  1.000000
2  0.666667  0.666667  0.666667
3  0.500000  0.500000  0.500000


In [ ]:
#in case of multiplication and addition since there is element wise commutative operation
# the output of df.mul() and df.rmul() will be same 
# the output of df.add() and df.radd() will be same 

print(df.mul(row, axis=1))# df*row
print("==========")
print(df.rmul(row, axis=1))#row*df


   A  B  C
0  2  2  2
1  4  4  4
2  6  6  6
3  8  8  8
   A  B  C
0  2  2  2
1  4  4  4
2  6  6  6
3  8  8  8


In [ ]:
print(df.add(row, axis=1)) #df value + row value 
print("==========")
print(df.radd(row, axis=1))# row value + df value

   A  B  C
0  3  3  3
1  4  4  4
2  5  5  5
3  6  6  6
   A  B  C
0  3  3  3
1  4  4  4
2  5  5  5
3  6  6  6


In [ ]:
df=pd.DataFrame({
    "values":[10,20,30,40]
}  
)

df

values
0      10
1      20
2      30
3      40

In [ ]:
#floor division //(largest integer less than or equal to the true quotient)
#(it just gives the whole number and not the fractional part of the division )

print(df.floordiv(3)) # df//3
print("==========")
print(df.rfloordiv(3)) #3//df

   values
0       3
1       6
2      10
3      13
   values
0       0
1       0
2       0
3       0


In [ ]:
#remainder

print(df.mod(3)) #df/3 value (df%3) remainder
print("==========")
print(df.rmod(3)) #3/df value (3%df) remainder

   values
0       1
1       2
2       0
3       1
   values
0       3
1       3
2       3
3       3


In [ ]:
from decimal import Decimal

print(df.pow(3)) #df to the power 3 (df**3)
print("==========")
print(df.rpow(3)) #3 to power df (3**df) (wrong answer)

# here we may notice that the 4th result of the 3rd output is wrong since the number is  very very big
# so in this case we should use for large number output
print("==========")
print(df.rpow(Decimal(3)))# this is the correct output


   values
0    1000
1    8000
2   27000
3   64000
                values
0                59049
1           3486784401
2      205891132094649
3 -6289078614652622815
                 values
0                 59049
1            3486784401
2       205891132094649
3  12157665459056928801


In [ ]:
df=pd.DataFrame(
    [
        [22,45,54],
        [33,64,36],
        [23,45,67]
    ],
    columns=["one","two","three"],
    index=["a","b","c"]
)
df

one  two  three
a   22   45     54
b   33   64     36
c   23   45     67

In [ ]:
dfmi=df.copy()

In [ ]:
#first way of creating the multi index
dfmi.index=pd.MultiIndex.from_tuples(
    [
        (1,"a"),
        (2,"a"),
        (2,"b"),
    ],
    names=["first","second"]
)

In [ ]:
# second way to create the multi index
dfmi.index=pd.MultiIndex.from_arrays(
    [
        [1,2,2],
        ["a","a","b"]
    ],
    names=["first","second"]
)


In [ ]:
dfmi.sub(df["two"], axis=0, level="second")

one  two  three
first second                 
1     a       -23    0      9
2     a       -12   19     -9
      b       -41  -19      3

In [ ]:
dfmi.sub(dfmi["two"], axis=0, level="second")

one  two  three
first second                 
1     a       -23    0      9
2     a       -31    0    -28
      b       -22    0     22

In [ ]:
s=df.iloc[1,:]
print(s)

one      33
two      64
three    36
Name: b, dtype: int64


In [ ]:
d,r=divmod(s,3) # divmod() gives the floor division and remainder at same time
print(d)
print("====")
print(r)

one      11
two      21
three    12
Name: b, dtype: int64
====
one      0
two      1
three    0
Name: b, dtype: int64


In [ ]:
a=np.array(
    [
        s,
        [3,3,3],
        d,
        r
    ]
)
pd.DataFrame(a.T, columns=["series","divisor","floor division", "remainder"])

series  divisor  floor division  remainder
0      33        3              11          0
1      64        3              21          1
2      36        3              12          0

Missing data/operations with fill value

In [ ]:
a=np.ones((4,3), dtype=int)
df1=pd.DataFrame(a, columns=["col1","col2","col3"])
df1.at[1,"col2"]=None  #for replacing the ONLY SINGLE VALUE
df2=df1.copy()
df2.at[3,"col3"]=None


In [ ]:
df1

col1  col2  col3
0     1   1.0     1
1     1   NaN     1
2     1   1.0     1
3     1   1.0     1

In [ ]:
df2

col1  col2  col3
0     1   1.0   1.0
1     1   NaN   1.0
2     1   1.0   1.0
3     1   1.0   NaN

In [ ]:
# normal addition 

#notnull + notnull= notnull
#notnull+null=null
#null+notnull=null
#null+null=null

df1.add(df2) 

col1  col2  col3
0     2   2.0   2.0
1     2   NaN   2.0
2     2   2.0   2.0
3     2   2.0   NaN

In [ ]:
#notnull+notnull=notnull
#notnull+null(0)= notnull #when single null null value is considered zero 
#null(0)+notnull=notnull #when single null,null value is considerd zero 
#null+null=null  | both null is null
df1.add(df2, fill_value=0)

col1  col2  col3
0     2   2.0   2.0
1     2   NaN   2.0
2     2   2.0   2.0
3     2   2.0   1.0

Flexible comparison methods of series and dataframe 

In [ ]:
df1.eq(df2) #df1==df2


col1   col2   col3
0  True   True   True
1  True  False   True
2  True   True   True
3  True   True  False

In [ ]:
df1.ne(df2) #df1!=df2

col1   col2   col3
0  False  False  False
1  False   True  False
2  False  False  False
3  False  False   True

In [ ]:
df1.lt(df2) #df1<df2

col1   col2   col3
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False

In [ ]:
df1.gt(df2) #df1>df2

col1   col2   col3
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False

In [ ]:
df1.le(df2) #df1<=df2

col1   col2   col3
0  True   True   True
1  True  False   True
2  True   True   True
3  True   True  False

In [ ]:
df1.ge(df2) #df1>=df2

col1   col2   col3
0  True   True   True
1  True  False   True
2  True   True   True
3  True   True  False

Boolean reductions

In [ ]:
(df1>0).all()

col1     True
col2    False
col3     True
dtype: bool

In [ ]:
print((df1>0).all()) #all values of  col1 and col3 are greater than zero 
print("======")
print((df1>0).any()) #any

col1     True
col2    False
col3     True
dtype: bool
col1    True
col2    True
col3    True
dtype: bool


In [ ]:
print((df1>0).all().all()) #in df not all values are more greater than 0

False


In [ ]:
df2.empty

False

In [ ]:
df2.isna().any()

col1    False
col2     True
col3     True
dtype: bool

Comparing if objects are equivalent

In [ ]:
df1+df2

col1  col2  col3
0     2   2.0   2.0
1     2   NaN   2.0
2     2   2.0   2.0
3     2   2.0   NaN

In [ ]:
df1+df2==df1*2

col1   col2   col3
0  True   True   True
1  True  False   True
2  True   True   True
3  True   True  False

In [ ]:
(df1+df2==df1*2).all()

col1     True
col2    False
col3    False
dtype: bool

In [ ]:
np.nan==np.nan

False

In [ ]:
(df1+df2).eq(df1*2).all().all()

False

In [ ]:
(df1+df2).equals(df1*2)

False

combining overlapping datasets

A problem occasionally arising is the combination of two similar data sets where values in one are preferred over the other. An example would be two data series representing a particular economic indicator where one is considered to be of “higher quality”. However, the lower quality series might extend further back in history or have more complete data coverage. As such, we would like to combine two DataFrame objects where missing values in one DataFrame are conditionally filled with like-labeled values from the other DataFrame. The function implementing this operation is combine_first(), which we illustrate:

In [ ]:
df1=pd.DataFrame(
    {
        "A":[1.0, np.nan, 3.0, 5.0, np.nan],
        "B":[np.nan, 2.0, 3.0, np.nan, 6.0]
    }
)
df1

A    B
0  1.0  NaN
1  NaN  2.0
2  3.0  3.0
3  5.0  NaN
4  NaN  6.0

In [ ]:
df2=pd.DataFrame(
    {
        "A":[5.0, 2.0, 4.0, np.nan, 3.0, 7.0],
        "B":[np.nan, np.nan, 3.0, 4.0, 6.0, 8.0]
    }
)
df2

A    B
0  5.0  NaN
1  2.0  NaN
2  4.0  3.0
3  NaN  4.0
4  3.0  6.0
5  7.0  8.0

In [ ]:
df1.combine_first(df2) #df1 has priority over df2

A    B
0  1.0  NaN
1  2.0  2.0
2  3.0  3.0
3  5.0  4.0
4  3.0  6.0
5  7.0  8.0

Descriptive Statistics 