In [1303]:
import pandas as pd
import numpy as np

In [1304]:
#different ways of creating the series 
#when we have a known values in a list 
pd.Series([1,2,3,4], index=["a","b","c","d"])

a    1
b    2
c    3
d    4
dtype: int64

In [1305]:
#when we want to generate the series of random values
pd.Series(np.random.randn(5), index=["a","b","c","d","e"])

a   -0.180525
b   -0.603063
c    1.831231
d    1.836432
e    0.630274
dtype: float64

In [1306]:
#when we have a single scaler value and want to create the series from it 
pd.Series(5, index=[1,2,3,4,5]) # the series will have the length of index thus the index can not be neglected in this case

1    5
2    5
3    5
4    5
5    5
dtype: int64

In [1307]:
#we can also create when in range

pd.Series(range(5), index=["a","b","c","d","e"])

a    0
b    1
c    2
d    3
e    4
dtype: int64

In [1308]:
#from a array 
a=np.array([1,2,3,4])

pd.Series(a, index=["b","a","c","d"])

b    1
a    2
c    3
d    4
dtype: int32

In [1309]:
#if we have different start stop and steps given and we want to create a series
#first create a array of it 
a=np.arange(start=2, stop=9, step=3, dtype=float)
pd.Series(a, index=["a","b","c"])

a    2.0
b    5.0
c    8.0
dtype: float64

In [1310]:
#whne number of points to be generated is known 
#then from start and stop point equi distance points can be generated 
a=np.linspace(start=2, stop=5, num=5) 
pd.Series(a, index=["a","b","c","d","e"])

a    2.00
b    2.75
c    3.50
d    4.25
e    5.00
dtype: float64

In [1311]:
#from a dictionary
d={
    "a":1,
    "c":34,
    "d":"128kg",
    "n":"Apple"
}

pd.Series(d)

a        1
c       34
d    128kg
n    Apple
dtype: object

In [1312]:
#from string 
pd.Series("name_1 name_2 city title".split())

0    name_1
1    name_2
2      city
3     title
dtype: object

In [1313]:
#making array of zeroes
np.zeros(shape=(3,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [1314]:
#making array of ones
np.ones(shape=(3,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [1315]:
#making identical matrix of array
np.eye(N=3, M=4, k=0, dtype=int) #k position of 1

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0]])

In [1316]:
#making a array from the provided list 

np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [1317]:
np.random.randn(3) #array of random values

array([-1.54377363, -1.24485778,  1.22651938])

In [1318]:
np.array(object=[1,2,3,4,5], dtype=float)

array([1., 2., 3., 4., 5.])

In [1319]:
pd.Series(
    data=[1,2,3,4,5],
    index=["a","b","c","d","e"]
)

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [1320]:
pd.Series(
    data=4,
    index=["a","b","c"]
)

a    4
b    4
c    4
dtype: int64

In [1321]:
pd.Series(
    data=np.random.randn(5),
    index=[1,2,3,4,5]
)

1    1.695246
2   -0.561042
3    0.623535
4   -1.443900
5   -0.681332
dtype: float64

In [1322]:
pd.Series(
    data=range(4),
    index=["a","b","c","d"]
)

a    0
b    1
c    2
d    3
dtype: int64

In [1323]:
pd.Series(
    data=np.arange(
        start=0,
        stop=11,
        step=2
    )
)

0     0
1     2
2     4
3     6
4     8
5    10
dtype: int32

In [1324]:
pd.Series(
    data=np.linspace(
        start=0,
        stop=11,
        num=4,
        dtype=float
    )
)

0     0.000000
1     3.666667
2     7.333333
3    11.000000
dtype: float64

In [1325]:
pd.Series(
    data={
        "a":1,
        "b":2,
        "c":3
    }
)

a    1
b    2
c    3
dtype: int64

In [1326]:
np.zeros(
    shape=(3,3),
    dtype=int
)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [1327]:
np.ones(
    shape=(4,4),
    dtype=int
)


array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [1328]:
3#remember 
np.eye(
    N=4,
    M=3,
    k=0,
    dtype=int
)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 0]])

In [1329]:
np.arange(
    start=2,
    stop=7,
    step=2,
    dtype=int
)

array([2, 4, 6])

In [1330]:
np.linspace(
    start=1,
    stop=10,
    num=4
)

array([ 1.,  4.,  7., 10.])

In [1331]:
#series from a given list
pd.Series(
    data=[1,2,3,4],
    index=["a","b","c","d"]
)

a    1
b    2
c    3
d    4
dtype: int64

In [1332]:
#series of random numbers 
pd.Series(
    data=np.random.randn(5),
    index=["a","b","c","d","e"],
)

a    0.338753
b    0.423111
c    0.708314
d    0.180821
e   -0.831407
dtype: float64

In [1333]:
#series of fixed scaler value
pd.Series(
    data=5,
    index=["a","b","c"]
)

a    5
b    5
c    5
dtype: int64

In [1334]:
pd.Series(
    data=range(5),
    index=["a","b","c","d","e"]
)

a    0
b    1
c    2
d    3
e    4
dtype: int64

In [1335]:
#when the distance between the values is fixed
pd.Series(
    data=np.arange(
        start=0,
        stop=11,
        step=2
    )
)

0     0
1     2
2     4
3     6
4     8
5    10
dtype: int32

In [1336]:
#when total number of values is decided 
pd.Series(
    data=np.linspace(
        start=0,
        stop=5,
        num=4
    )
    
)

0    0.000000
1    1.666667
2    3.333333
3    5.000000
dtype: float64

In [1337]:
pd.Series(
    data={
        "a":1,
        "b":2,
        "c":3
    }
)

a    1
b    2
c    3
dtype: int64

In [1338]:
np.zeros(
    shape=(3,3),
    dtype=int
)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [1339]:
np.ones(
    shape=(3,3),
    dtype=int
)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [1340]:
np.eye(
    N=3,
    M=4,
    k=1
)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [1341]:
np.diag(
    v=[1,2,3,4],
    k=2
)

array([[0, 0, 1, 0, 0, 0],
       [0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 3, 0],
       [0, 0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [1342]:
#random value array
np.array(
    object=np.random.randn(3,3),
    dtype=float,
)


array([[-1.43421718,  1.13440781,  0.59071391],
       [-0.54359431,  1.03845515, -0.28963109],
       [ 1.14984896, -1.16532743,  0.68430039]])

In [1343]:
# #random values in the memory at the location 
np.empty(
    shape=(3,3)
)

array([[1.43421718, 1.13440781, 0.59071391],
       [0.54359431, 1.03845515, 0.28963109],
       [1.14984896, 1.16532743, 0.68430039]])

In [1344]:
np.array(
    object=[
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ],
    dtype=float
)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [1345]:
np.random.randint(
    low=1,
    high=10,
    size=(3,4)
)

array([[3, 6, 9, 9],
       [3, 8, 6, 7],
       [3, 9, 9, 6]])

In [1346]:
np.arange(
    start=10,
    stop=20,
    step=3
)

array([10, 13, 16, 19])

In [1347]:
np.linspace(
    start=10,
    stop=20,
    num=3

)

array([10., 15., 20.])

In [1348]:
np.zeros(
    shape=(3,3),
    dtype=int
)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [1349]:
np.ones(
    shape=(3,3),
    dtype=int
)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [1350]:
np.eye(
    N=3,
    M=3,
    k=0,
    dtype=int
)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [1351]:
np.diag(
    v=[1,2,3],
    k=0,

)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [1352]:
#random float values
np.random.randn(
    3,3,
)

array([[ 0.50411075,  1.89105588, -0.15583535],
       [-0.32312642,  0.53210118,  1.2432806 ],
       [ 0.23723179,  1.39998812, -0.98587641]])

In [1353]:
#random intiger values
np.random.randint(
    low=10,
    high=20,
    size=(3,3)
)

array([[14, 18, 15],
       [12, 10, 15],
       [19, 19, 15]])

In [1354]:
#random values datatype can be controled
#but the values are from memory location

np.empty(
    shape=(3,3),
    dtype=int
)

array([[        0,         0, 992759984],
       [      420, 992756400,       420],
       [992758064,       420,   7602281]])

In [1355]:
#valus controlled
np.array(
    object=[
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [1356]:
np.arange(
    start=10,
    stop=20,
    step=2
)

array([10, 12, 14, 16, 18])

In [1357]:
#we can use reshape on any array to change its shape according to our need
np.linspace(
    start=10,
    stop=20,
    num=6
).reshape(3,2)

array([[10., 12.],
       [14., 16.],
       [18., 20.]])

In [1358]:
pd.DataFrame(
    {
        "col_1":[1,2,3],
        "col_2":["New York", "San Francisco", "Los Angeles"]
    }
)

col_1          col_2
0      1       New York
1      2  San Francisco
2      3    Los Angeles

In [1359]:
pd.DataFrame(
    {
        "col_1":pd.Series(
            data=[23,22,23,24,34]
        ),

        "col_2":np.linspace(
            start=20,
            stop=30,
            num=5
        ),

        "col_3":["New York", "San Francisco", "Los Angeles", "New York", "San Francisco"]  

    }
)

col_1  col_2          col_3
0     23   20.0       New York
1     22   22.5  San Francisco
2     23   25.0    Los Angeles
3     24   27.5       New York
4     34   30.0  San Francisco

In [1360]:
pd.DataFrame(
    data=pd.Series(
        data=[1,2,3,4],
        name="ser"
    )
)

ser
0    1
1    2
2    3
3    4

In [1361]:
pd.DataFrame(
    [
        [1, 1.0, "New York"],
        [2,2.0,"San Francisco"],
        [3,3.0, "Los Angeles"]
    ],
    columns=["col_1","col_2","col_3"]
)

col_1  col_2          col_3
0      1    1.0       New York
1      2    2.0  San Francisco
2      3    3.0    Los Angeles

In [1362]:
pd.DataFrame(
    data=np.random.randint(
        low=20,
        high=40,
        size=(4,3)
    ),
    columns=["col_1","col_2","col_3"]
)

col_1  col_2  col_3
0     33     22     22
1     21     24     20
2     36     23     26
3     22     29     20

In [1363]:
pd.DataFrame.from_dict(
    dict(
        [
            ("A",[1,2,3]),
            ("B",[3,4,5])
        ]
    )
)

A  B
0  1  3
1  2  4
2  3  5

In [1364]:
pd.DataFrame.from_dict(
    dict(
        [
            ["A",[1,2,3]],
            ["B",[2,3,4]]
        ]
    )
)

A  B
0  1  2
1  2  3
2  3  4

In [1365]:
np.zeros(
    shape=(3,3),
    dtype=int
)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [1366]:
np.ones(
    shape=(3,3),
    dtype=int
)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [1367]:
np.eye(
    N=3,
    M=4,
    k=0,
    dtype=int
)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0]])

In [1368]:
np.diag(
    v=[1,2,44,5,6],
    k=1
)

array([[ 0,  1,  0,  0,  0,  0],
       [ 0,  0,  2,  0,  0,  0],
       [ 0,  0,  0, 44,  0,  0],
       [ 0,  0,  0,  0,  5,  0],
       [ 0,  0,  0,  0,  0,  6],
       [ 0,  0,  0,  0,  0,  0]])

In [1369]:
np.random.randn(4,4)

array([[ 0.18267432, -0.57834255, -0.68381431, -0.81172567],
       [-1.83572008,  0.45074732,  2.01929884, -1.96813978],
       [ 0.58055945, -0.14697197, -1.23313959, -0.71340271],
       [-0.63741181,  1.27254236,  1.38425852, -1.05987484]])

In [1370]:
np.random.randint(
    low=10,
    high=20,
    size=(3,3),
    dtype=int
)

array([[16, 17, 14],
       [11, 14, 14],
       [11, 10, 18]])

In [1371]:
np.arange(
    start=10,
    stop=26,
    step=3
).reshape(2,3)

array([[10, 13, 16],
       [19, 22, 25]])

In [1372]:
np.linspace(
    start=10,
    stop=26,
    num=6
).reshape(2,3)

array([[10. , 13.2, 16.4],
       [19.6, 22.8, 26. ]])

In [1373]:
np.empty(
    shape=(4,4),
    dtype=int
)

array([[         0, 1072693248,          0,          0],
       [         0, 1073741824,          0,          0],
       [         0, 1074266112,          0,          0],
       [         0, 1074790400,          0,          0]])

In [1374]:
np.array(
    object=[
        [1,2,3,4],
        [5,6,7,8],
        [9,10,11,12]
    ]
).reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [1375]:
pd.Series(
    data=[1,2,3,4,5],
    index=["a","b","c","d","e"]
)

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [1376]:
pd.Series(
    data=5, 
    index=["a","b","c"]
)

a    5
b    5
c    5
dtype: int64

In [1377]:
pd.Series(
    data=np.random.randint(
        low=3,
        high=10,
        size=(4,)
    ),
    index=["a","b","c","d"]
)

C:\Users\aadit\AppData\Roaming\Python\Python311\site-packages\IPython\core\displayhook.py:281: UserWarning: Output cache limit (currently 1000 entries) hit.
Flushing oldest 200 entries.
  warn('Output cache limit (currently {sz} entries) hit.\n'


a    8
b    4
c    4
d    6
dtype: int32

In [1378]:
pd.Series(
    data=range(5),
    index=["a","b","c","d","e"]
)

a    0
b    1
c    2
d    3
e    4
dtype: int64

In [1379]:
pd.DataFrame(
    data={
        "col_1":pd.Series(
            range(5)
        ),
        "col_2": np.linspace(
            start=10,
            stop=20,
            num=5
        ),
        "col_3":("New York", "Delhi", "Mumbai", "Sydney", " ")
    }
)

col_1  col_2     col_3
0      0   10.0  New York
1      1   12.5     Delhi
2      2   15.0    Mumbai
3      3   17.5    Sydney
4      4   20.0

In [1380]:
pd.DataFrame(
    data=np.random.randint(
        low=20,
        high=40,
        size=(5,3)
    ),
    columns=["col_1","col_2","col_3"],
    index=[1,2,3,4,5]
)

col_1  col_2  col_3
1     26     37     33
2     35     27     31
3     39     22     25
4     23     21     22
5     30     26     25

In [1381]:
data_1=pd.DataFrame(
    data=[
        [1,2,3,4],
        [3,4,5,6],
        [7,8,9,10]
    ],
    columns=["A","B","C","D"]
)

In [1382]:
data_1

A  B  C   D
0  1  2  3   4
1  3  4  5   6
2  7  8  9  10

In [1383]:
data_1["A"]

0    1
1    3
2    7
Name: A, dtype: int64

In [1384]:
data_1[["A"]]

A
0  1
1  3
2  7

In [1385]:
data_1.iloc[:,0]

0    1
1    3
2    7
Name: A, dtype: int64

In [1386]:
data_1.iloc[0:2,0:2]

A  B
0  1  2
1  3  4

In [1387]:
data_1.loc[:,"A"]

0    1
1    3
2    7
Name: A, dtype: int64

In [1388]:
data_1.loc[[0,2], ["A","B"]]

A  B
0  1  2
2  7  8

In [1389]:
data_1.iloc[:,[0,1]]

A  B
0  1  2
1  3  4
2  7  8

In [1390]:
data_1.loc[
    :,
    "A":"B"
]

A  B
0  1  2
1  3  4
2  7  8

In [1391]:
data_1.iloc[
    :,
    0:2
]

A  B
0  1  2
1  3  4
2  7  8

In [1392]:
data_1.loc[
    [0,2],
    ["A","C"]
]

A  C
0  1  3
2  7  9

In [1393]:
data_1.iloc[
    [0,2],
    [1,2]

]

B  C
0  2  3
2  8  9

In [1394]:
data_1[0:2][["A"]]

A
0  1
1  3

In [1395]:
data_1[:][["A","B"]]

A  B
0  1  2
1  3  4
2  7  8

In [1396]:
data_1[1:3][["A","B"]]

A  B
1  3  4
2  7  8

In [1397]:
df1=pd.DataFrame(
    data=np.random.randint(
        low=1, 
        high=5,
        size=(3,3),
    ),
    columns=["A","B","C"]
)
df1

A  B  C
0  2  4  4
1  1  1  3
2  3  1  2

In [1398]:
df2=pd.DataFrame(
    data=np.diag(
        v=[2,4,6,8]
    ),
    columns=["A","B","C", "D"]
)
df2

A  B  C  D
0  2  0  0  0
1  0  4  0  0
2  0  0  6  0
3  0  0  0  8

In [1399]:
df1+df2

A    B    C   D
0  4.0  4.0  4.0 NaN
1  1.0  5.0  3.0 NaN
2  3.0  1.0  8.0 NaN
3  NaN  NaN  NaN NaN

In [1400]:
df1[["D"]]=df1.loc[[0],["C"]]

In [1401]:
df1+df2 #anything  + NAN =NAN

A    B    C    D
0  4.0  4.0  4.0  4.0
1  1.0  5.0  3.0  NaN
2  3.0  1.0  8.0  NaN
3  NaN  NaN  NaN  NaN

In [1402]:
df1=pd.DataFrame(
    data=np.random.randint(
        low=0,
        high=2,
        size=(2,2)
    ),
    columns=["A","B",],
    dtype=bool
)

In [1403]:
df1

A      B
0  True   True
1  True  False

In [1404]:
df2=pd.DataFrame(
    data=np.random.randint(
        low=0,
        high=2,
        size=(2,2),
    ),
    columns=["A","B"],
    dtype=bool
)
df2

A      B
0  False   True
1  False  False

In [1405]:
df1+df2

A      B
0  True   True
1  True  False

In [1406]:
df1&df2

A      B
0  False   True
1  False  False

In [1407]:
df1|df2

A      B
0  True   True
1  True  False

In [1408]:
s=pd.Series(np.random.randn(5))
subset=s[1:4]

In [1409]:
s

0    0.689738
1    1.070125
2    0.235963
3   -0.365091
4    0.464582
dtype: float64

In [1410]:
subset

1    1.070125
2    0.235963
3   -0.365091
dtype: float64

In [1411]:
subset[2]=99

In [1412]:
a=np.random.randn(5)
subset_a=a[1:4]

In [1413]:
a

array([-0.25470391,  0.46816067,  0.32036352,  1.3453767 , -0.28062636])

In [1414]:
subset_a

array([0.46816067, 0.32036352, 1.3453767 ])

In [1415]:
subset_a[1]=99

In [1416]:
type(s)

pandas.core.series.Series

In [1417]:
s.dtype

dtype('float64')

In [1418]:
s.to_numpy()

array([ 0.68973836,  1.07012482, 99.        , -0.36509116,  0.46458187])

In [1419]:
df=pd.DataFrame(
    data=np.random.randint(
        low=10,
        high=50,
        size=(8,3)
    ),
    columns=["col_1","col_2","col_3"],
    index=pd.date_range("1/1/2000", periods=8)
)

In [1420]:
df

col_1  col_2  col_3
2000-01-01     21     21     38
2000-01-02     23     14     13
2000-01-03     20     23     24
2000-01-04     17     22     28
2000-01-05     44     29     32
2000-01-06     46     48     45
2000-01-07     36     39     27
2000-01-08     39     10     14

In [1421]:
df.shape

(8, 3)

In [1422]:
df.index

DatetimeIndex(['2000-01-01', '2000-01-02', '2000-01-03', '2000-01-04',
               '2000-01-05', '2000-01-06', '2000-01-07', '2000-01-08'],
              dtype='datetime64[ns]', freq='D')

In [1423]:
df.columns

Index(['col_1', 'col_2', 'col_3'], dtype='object')

In [1424]:
df.values

array([[21, 21, 38],
       [23, 14, 13],
       [20, 23, 24],
       [17, 22, 28],
       [44, 29, 32],
       [46, 48, 45],
       [36, 39, 27],
       [39, 10, 14]])

In [1425]:
df.axes

[DatetimeIndex(['2000-01-01', '2000-01-02', '2000-01-03', '2000-01-04',
                '2000-01-05', '2000-01-06', '2000-01-07', '2000-01-08'],
               dtype='datetime64[ns]', freq='D'),
 Index(['col_1', 'col_2', 'col_3'], dtype='object')]

In [1426]:
df.ndim

2

In [1427]:
df.size

24

In [1428]:
df.dtypes

col_1    int32
col_2    int32
col_3    int32
dtype: object

In [1429]:
df.shape

(8, 3)

In [1430]:
df.index

DatetimeIndex(['2000-01-01', '2000-01-02', '2000-01-03', '2000-01-04',
               '2000-01-05', '2000-01-06', '2000-01-07', '2000-01-08'],
              dtype='datetime64[ns]', freq='D')

In [1431]:
df.columns

Index(['col_1', 'col_2', 'col_3'], dtype='object')

In [1432]:
df.values

array([[21, 21, 38],
       [23, 14, 13],
       [20, 23, 24],
       [17, 22, 28],
       [44, 29, 32],
       [46, 48, 45],
       [36, 39, 27],
       [39, 10, 14]])

In [1433]:
df.size

24

In [1434]:
df.dtypes

col_1    int32
col_2    int32
col_3    int32
dtype: object

In [1435]:
type(df)

pandas.core.frame.DataFrame

In [1436]:
df.describe()

col_1     col_2     col_3
count   8.000000   8.00000   8.00000
mean   30.750000  25.75000  27.62500
std    11.732129  12.60102  10.96667
min    17.000000  10.00000  13.00000
25%    20.750000  19.25000  21.50000
50%    29.500000  22.50000  27.50000
75%    40.250000  31.50000  33.50000
max    46.000000  48.00000  45.00000

In [1437]:
df.select_dtypes(include=int)

col_1  col_2  col_3
2000-01-01     21     21     38
2000-01-02     23     14     13
2000-01-03     20     23     24
2000-01-04     17     22     28
2000-01-05     44     29     32
2000-01-06     46     48     45
2000-01-07     36     39     27
2000-01-08     39     10     14

In [1438]:
df.head()

col_1  col_2  col_3
2000-01-01     21     21     38
2000-01-02     23     14     13
2000-01-03     20     23     24
2000-01-04     17     22     28
2000-01-05     44     29     32

In [1439]:
df.tail()

col_1  col_2  col_3
2000-01-04     17     22     28
2000-01-05     44     29     32
2000-01-06     46     48     45
2000-01-07     36     39     27
2000-01-08     39     10     14

In [1440]:
df.sample(3)

col_1  col_2  col_3
2000-01-08     39     10     14
2000-01-03     20     23     24
2000-01-01     21     21     38

In [1441]:
df.nunique()

col_1    8
col_2    8
col_3    8
dtype: int64

In [1442]:
df["col_1"].unique()

array([21, 23, 20, 17, 44, 46, 36, 39])

In [1443]:
df.count()

col_1    8
col_2    8
col_3    8
dtype: int64

In [1444]:
df.mean()

col_1    30.750
col_2    25.750
col_3    27.625
dtype: float64

In [1445]:
df.max()

col_1    46
col_2    48
col_3    45
dtype: int32

In [1446]:
df.median()

col_1    29.5
col_2    22.5
col_3    27.5
dtype: float64

In [1447]:
df.min()

col_1    17
col_2    10
col_3    13
dtype: int32

In [1448]:
df.sum()

col_1    246
col_2    206
col_3    221
dtype: int64

In [1449]:
df.isnull()

col_1  col_2  col_3
2000-01-01  False  False  False
2000-01-02  False  False  False
2000-01-03  False  False  False
2000-01-04  False  False  False
2000-01-05  False  False  False
2000-01-06  False  False  False
2000-01-07  False  False  False
2000-01-08  False  False  False

In [1450]:
df.isnull().sum()

col_1    0
col_2    0
col_3    0
dtype: int64

In [1451]:
df.notnull().sum()

col_1    8
col_2    8
col_3    8
dtype: int64

In [1452]:
df.duplicated().sum()

0

In [1453]:
df.shape

(8, 3)

In [1454]:
df.index

DatetimeIndex(['2000-01-01', '2000-01-02', '2000-01-03', '2000-01-04',
               '2000-01-05', '2000-01-06', '2000-01-07', '2000-01-08'],
              dtype='datetime64[ns]', freq='D')

In [1455]:
df.columns

Index(['col_1', 'col_2', 'col_3'], dtype='object')

In [1456]:
df.values

array([[21, 21, 38],
       [23, 14, 13],
       [20, 23, 24],
       [17, 22, 28],
       [44, 29, 32],
       [46, 48, 45],
       [36, 39, 27],
       [39, 10, 14]])

In [1457]:
df.sample(3)

col_1  col_2  col_3
2000-01-06     46     48     45
2000-01-05     44     29     32
2000-01-03     20     23     24

In [1458]:
df.head()

col_1  col_2  col_3
2000-01-01     21     21     38
2000-01-02     23     14     13
2000-01-03     20     23     24
2000-01-04     17     22     28
2000-01-05     44     29     32

In [1459]:
df.tail()

col_1  col_2  col_3
2000-01-04     17     22     28
2000-01-05     44     29     32
2000-01-06     46     48     45
2000-01-07     36     39     27
2000-01-08     39     10     14

In [1460]:
df.nunique()

col_1    8
col_2    8
col_3    8
dtype: int64

In [1461]:
df["col_1"].unique()

array([21, 23, 20, 17, 44, 46, 36, 39])

In [1462]:
df.isnull().sum()

col_1    0
col_2    0
col_3    0
dtype: int64

In [1463]:
df.notnull().sum()

col_1    8
col_2    8
col_3    8
dtype: int64

In [1464]:
df.duplicated().sum()

0

In [1465]:
ser=pd.Series(pd.date_range("2010", periods=2, tz="Australia/Sydney"))

In [1466]:
ser

0   2010-01-01 00:00:00+11:00
1   2010-01-02 00:00:00+11:00
dtype: datetime64[ns, Australia/Sydney]

In [1467]:
ser=pd.Series(pd.date_range("2010", periods=2, tz="Australia/Sydney"))
ser.to_numpy(dtype="datetime64[ns]")

array(['2009-12-31T13:00:00.000000000', '2010-01-01T13:00:00.000000000'],
      dtype='datetime64[ns]')

In [1468]:
import pandas as pd
import pytz

ser=pd.to_datetime('2009-12-31T13:00:00.000000000', utc=True)
ser_sydney=ser.tz_convert("Australia/Sydney")

In [1469]:
ser_sydney

Timestamp('2010-01-01 00:00:00+1100', tz='Australia/Sydney')

In [1470]:
ser=pd.Series(pd.date_range("2010", periods=2, tz="Australia/Sydney"))
ser.to_numpy(dtype="timedelta64[ns]")

array([1262264400000000000, 1262350800000000000], dtype='timedelta64[ns]')

In [1471]:
ser=pd.Series(
    data=pd.date_range(
        start="2000",
        periods=2,
        tz="Australia/Sydney"
    )
)

ser.to_numpy(
    dtype="object"
)


array([Timestamp('2000-01-01 00:00:00+1100', tz='Australia/Sydney'),
       Timestamp('2000-01-02 00:00:00+1100', tz='Australia/Sydney')],
      dtype=object)

In [1472]:
ser.to_numpy(dtype="datetime64[ns]")

array(['1999-12-31T13:00:00.000000000', '2000-01-01T13:00:00.000000000'],
      dtype='datetime64[ns]')

In [1473]:
ser.to_numpy(dtype="timedelta64[ns]")

array([946645200000000000, 946731600000000000], dtype='timedelta64[ns]')

In [1474]:
df1=pd.DataFrame(
    data=np.random.randint(
        low=1,
        high=6,
        size=(4,2)
    ),
    columns=["col_1","col_2"]
)
df1

col_1  col_2
0      2      1
1      4      4
2      3      2
3      4      3

In [1475]:
df2=pd.DataFrame(
    data=np.random.randint(
        low=1,
        high=6,
        size=(3,3)
    ),
    columns=["col_1","col_2", "col_3"]
)
df2

col_1  col_2  col_3
0      4      3      1
1      4      2      5
2      1      3      4

In [1476]:
df1

col_1  col_2
0      2      1
1      4      4
2      3      2
3      4      3

In [1477]:
row=df1.iloc[1,:]
df1.sub(row, axis=1)

col_1  col_2
0     -2     -3
1      0      0
2     -1     -2
3      0     -1

In [1478]:
df2.sub(row, axis=1)

col_1  col_2  col_3
0    0.0   -1.0    NaN
1    0.0   -2.0    NaN
2   -3.0   -1.0    NaN

In [1479]:
df1.rsub(row, axis=1)

col_1  col_2
0      2      3
1      0      0
2      1      2
3      0      1

In [1480]:
df2.rsub(row, axis=1)

col_1  col_2  col_3
0    0.0    1.0    NaN
1    0.0    2.0    NaN
2    3.0    1.0    NaN

In [1481]:
col=df1.iloc[:,0]
df1.sub(col, axis=0)

col_1  col_2
0      0     -1
1      0      0
2      0     -1
3      0     -1

In [1482]:
col

0    2
1    4
2    3
3    4
Name: col_1, dtype: int32

In [1483]:
df1

col_1  col_2
0      2      1
1      4      4
2      3      2
3      4      3

In [1484]:
df2

col_1  col_2  col_3
0      4      3      1
1      4      2      5
2      1      3      4

In [1485]:
df1.sub(col, axis=0)

col_1  col_2
0      0     -1
1      0      0
2      0     -1
3      0     -1

In [1486]:
df2.sub(col, axis=0)

col_1  col_2  col_3
0    2.0    1.0   -1.0
1    0.0   -2.0    1.0
2   -2.0    0.0    1.0
3    NaN    NaN    NaN

In [1487]:
df1.rsub(col, axis=0)

col_1  col_2
0      0      1
1      0      0
2      0      1
3      0      1

In [1488]:
df2.rsub(col, axis=0)

col_1  col_2  col_3
0   -2.0   -1.0    1.0
1    0.0    2.0   -1.0
2    2.0    0.0   -1.0
3    NaN    NaN    NaN

In [1489]:
df1.sub(df2)

col_1  col_2  col_3
0   -2.0   -2.0    NaN
1    0.0    2.0    NaN
2    2.0   -1.0    NaN
3    NaN    NaN    NaN

In [1490]:
df1

col_1  col_2
0      2      1
1      4      4
2      3      2
3      4      3

In [1491]:
df2

col_1  col_2  col_3
0      4      3      1
1      4      2      5
2      1      3      4

In [1492]:
df1.div(3)

col_1     col_2
0  0.666667  0.333333
1  1.333333  1.333333
2  1.000000  0.666667
3  1.333333  1.000000

In [1493]:
df1[["col_1"]].div(3)

col_1
0  0.666667
1  1.333333
2  1.000000
3  1.333333

In [1494]:
df1[1:3][["col_1"]].div(3)

col_1
1  1.333333
2  1.000000

In [1495]:
row1=df2.iloc[2,:]
col1=df2.iloc[:,1]

In [1496]:
df1.div(row1, axis=1)

col_1     col_2  col_3
0    2.0  0.333333    NaN
1    4.0  1.333333    NaN
2    3.0  0.666667    NaN
3    4.0  1.000000    NaN

In [1497]:
df1.rdiv(row1, axis=1)

col_1  col_2  col_3
0  0.500000   3.00    NaN
1  0.250000   0.75    NaN
2  0.333333   1.50    NaN
3  0.250000   1.00    NaN

In [1498]:
df2.div(row1,axis=1)

col_1     col_2  col_3
0    4.0  1.000000   0.25
1    4.0  0.666667   1.25
2    1.0  1.000000   1.00

In [1499]:
df2.rdiv(row1, axis=1)

col_1  col_2  col_3
0   0.25    1.0    4.0
1   0.25    1.5    0.8
2   1.00    1.0    1.0

In [1500]:
df1.div(col1, axis=0)

col_1     col_2
0  0.666667  0.333333
1  2.000000  2.000000
2  1.000000  0.666667
3       NaN       NaN

In [1501]:
df1.rdiv(col1, axis=0)

col_1  col_2
0    1.5    3.0
1    0.5    0.5
2    1.0    1.5
3    NaN    NaN

In [1502]:
df2.div(col1, axis=0)

col_1  col_2     col_3
0  1.333333    1.0  0.333333
1  2.000000    1.0  2.500000
2  0.333333    1.0  1.333333

In [1503]:
df2.rdiv(col1, axis=0)

col_1  col_2  col_3
0   0.75    1.0   3.00
1   0.50    1.0   0.40
2   3.00    1.0   0.75

In [1504]:
df1.mul(row1, axis=1)

col_1  col_2  col_3
0      2      3    NaN
1      4     12    NaN
2      3      6    NaN
3      4      9    NaN

In [1505]:
df1.rmul(row1, axis=1)

col_1  col_2  col_3
0      2      3    NaN
1      4     12    NaN
2      3      6    NaN
3      4      9    NaN

In [1506]:
df2.mul(row1, axis=1)

col_1  col_2  col_3
0      4      9      4
1      4      6     20
2      1      9     16

In [1507]:
df2.rmul(row1, axis=1)

col_1  col_2  col_3
0      4      9      4
1      4      6     20
2      1      9     16

In [1508]:
df1.mul(col1, axis=0)

col_1  col_2
0    6.0    3.0
1    8.0    8.0
2    9.0    6.0
3    NaN    NaN

In [1509]:
df2.mul(col1, axis=0)

col_1  col_2  col_3
0     12      9      3
1      8      4     10
2      3      9     12

In [1510]:
df1.rmul(col1, axis=0)

col_1  col_2
0    6.0    3.0
1    8.0    8.0
2    9.0    6.0
3    NaN    NaN

In [1511]:
df2.rmul(col1, axis=0)

col_1  col_2  col_3
0     12      9      3
1      8      4     10
2      3      9     12

In [1512]:
df1.add(row1, axis=1)

col_1  col_2  col_3
0      3      4    NaN
1      5      7    NaN
2      4      5    NaN
3      5      6    NaN

In [1513]:
df1.radd(row1, axis=1)

col_1  col_2  col_3
0      3      4    NaN
1      5      7    NaN
2      4      5    NaN
3      5      6    NaN

In [1514]:
df2.add(row1, axis=1)

col_1  col_2  col_3
0      5      6      5
1      5      5      9
2      2      6      8

In [1515]:
df2.radd(row1, axis=1)

col_1  col_2  col_3
0      5      6      5
1      5      5      9
2      2      6      8

In [1516]:
df1.add(col1, axis=0)

col_1  col_2
0    5.0    4.0
1    6.0    6.0
2    6.0    5.0
3    NaN    NaN

In [1517]:
df1.radd(col1, axis=0)

col_1  col_2
0    5.0    4.0
1    6.0    6.0
2    6.0    5.0
3    NaN    NaN

In [1518]:
df2.add(col1, axis=0)

col_1  col_2  col_3
0      7      6      4
1      6      4      7
2      4      6      7

In [1519]:
df2.add(col1, axis=0)

col_1  col_2  col_3
0      7      6      4
1      6      4      7
2      4      6      7

In [1520]:
df2

col_1  col_2  col_3
0      4      3      1
1      4      2      5
2      1      3      4

In [1521]:
df1

col_1  col_2
0      2      1
1      4      4
2      3      2
3      4      3

In [1522]:
df1.rfloordiv(2)

col_1  col_2
0      1      2
1      0      0
2      0      1
3      0      0

In [1523]:
df2.floordiv(2)

col_1  col_2  col_3
0      2      1      0
1      2      1      2
2      0      1      2

In [1524]:
df2.rfloordiv(2)

col_1  col_2  col_3
0      0      0      2
1      0      1      0
2      2      0      0

In [1525]:
df1.mod(2)

col_1  col_2
0      0      1
1      0      0
2      1      0
3      0      1

In [1526]:
df1

col_1  col_2
0      2      1
1      4      4
2      3      2
3      4      3

In [1527]:
df1.rmod(2)

col_1  col_2
0      0      0
1      2      2
2      2      0
3      2      2

In [1528]:
df2.mod(3)

col_1  col_2  col_3
0      1      0      1
1      1      2      2
2      1      0      1

In [1529]:
df2.rmod(2)

col_1  col_2  col_3
0      2      2      0
1      2      0      2
2      0      2      2

In [1530]:
df1.pow(2)

col_1  col_2
0      4      1
1     16     16
2      9      4
3     16      9

In [1531]:
df1.rpow(2)

col_1  col_2
0      4      2
1     16     16
2      8      4
3     16      8

In [1532]:
df2.pow(2)

col_1  col_2  col_3
0     16      9      1
1     16      4     25
2      1      9     16

In [1533]:
df2.rpow(2)

col_1  col_2  col_3
0     16      8      2
1     16      4     32
2      2      8     16

In [1534]:
d,r=divmod(df1, 2)
d

col_1  col_2
0      1      0
1      2      2
2      1      1
3      2      1

In [1535]:
df2-row1

col_1  col_2  col_3
0      3      0     -3
1      3     -1      1
2      0      0      0

In [1536]:
row1-df2

col_1  col_2  col_3
0     -3      0      3
1     -3      1     -1
2      0      0      0

In [1537]:
df1

col_1  col_2
0      2      1
1      4      4
2      3      2
3      4      3

In [1538]:
df2

col_1  col_2  col_3
0      4      3      1
1      4      2      5
2      1      3      4

In [1539]:
df1

col_1  col_2
0      2      1
1      4      4
2      3      2
3      4      3

In [1540]:
df2.index=pd.MultiIndex.from_arrays(
    [
        [1,2,3],
        ["a","b","c"]
    ],
    names=["first","second"]
)

In [1541]:
df2.rsub(df1["col_1"], axis=0, level="second")

col_1  col_2  col_3
first second                     
1     a         NaN    NaN    NaN
2     b         NaN    NaN    NaN
3     c         NaN    NaN    NaN

In [1542]:
df1.iloc[1,:]

col_1    4
col_2    4
Name: 1, dtype: int32

In [1543]:
df1

col_1  col_2
0      2      1
1      4      4
2      3      2
3      4      3

In [1544]:
df1

col_1  col_2
0      2      1
1      4      4
2      3      2
3      4      3

In [1545]:
df2

col_1  col_2  col_3
first second                     
1     a           4      3      1
2     b           4      2      5
3     c           1      3      4

In [1546]:
df1

col_1  col_2
0      2      1
1      4      4
2      3      2
3      4      3

In [1547]:
df1.reset_index(drop=True)


col_1  col_2
0      2      1
1      4      4
2      3      2
3      4      3

In [1548]:
df1.at[0, "col_1"]=None

In [1549]:
df1.at[2,"col_2"]=None

In [1558]:
df1

col_1  col_2
0    NaN    1.0
1    4.0    4.0
2    3.0    NaN
3    4.0    3.0

In [1561]:
df2=df2.reset_index(drop=True)

In [1562]:
df2

col_1  col_2  col_3
0    NaN      3      1
1    4.0      2      5
2    1.0      3      4

In [1563]:
df2.at[1,"col_1"]=None

In [1565]:
df1

col_1  col_2
0    NaN    1.0
1    4.0    4.0
2    3.0    NaN
3    4.0    3.0

In [1564]:
df2

col_1  col_2  col_3
0    NaN      3      1
1    NaN      2      5
2    1.0      3      4

In [1566]:
df1+df2

col_1  col_2  col_3
0    NaN    4.0    NaN
1    NaN    6.0    NaN
2    4.0    NaN    NaN
3    NaN    NaN    NaN

In [1568]:
df1.add(df2,fill_value=0)

col_1  col_2  col_3
0    NaN    4.0    1.0
1    4.0    6.0    5.0
2    4.0    3.0    4.0
3    4.0    3.0    NaN

In [1569]:
#flexible comparison methods of series and datafrme

In [1571]:
df1.eq(df2) #df1==df2

col_1  col_2  col_3
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False

In [1572]:
df1.ne(df2) #df1!=df2

col_1  col_2  col_3
0   True   True   True
1   True   True   True
2   True   True   True
3   True   True   True

In [1574]:
df1.loc[:,"col_1"].eq(df2.loc[:,"col_1"])

0    False
1    False
2    False
3    False
Name: col_1, dtype: bool

In [1575]:
df1.lt(df2) #df1<df2

col_1  col_2  col_3
0  False   True  False
1  False  False  False
2  False  False  False
3  False  False  False

In [1576]:
df1.gt(df2) #df1>df2

col_1  col_2  col_3
0  False  False  False
1  False   True  False
2   True  False  False
3  False  False  False

In [ ]:
df1.le(df2) #df1<=df2

In [1577]:
df1.ge(df2) #df1>=df2

col_1  col_2  col_3
0  False  False  False
1  False   True  False
2   True  False  False
3  False  False  False

In [1578]:
(df1>0).all()

col_1    False
col_2    False
dtype: bool

In [1579]:
(df1>0).any()

col_1    True
col_2    True
dtype: bool

In [1580]:
(df1>0).all().all()

False

In [1581]:
df2.isna().any()

col_1     True
col_2    False
col_3    False
dtype: bool

In [1583]:
df1

col_1  col_2
0    NaN    1.0
1    4.0    4.0
2    3.0    NaN
3    4.0    3.0

In [1584]:
df2

col_1  col_2  col_3
0    NaN      3      1
1    NaN      2      5
2    1.0      3      4

In [1585]:
df1.combine_first(df2)

col_1  col_2  col_3
0    NaN    1.0    1.0
1    4.0    4.0    5.0
2    3.0    3.0    4.0
3    4.0    3.0    NaN

In [2]:
import numpy as np
import pandas as pd

In [4]:
a1=np.arange(
    start=0, 
    stop=10,
    step=3
)
a1

array([0, 3, 6, 9])

In [7]:
a2=np.linspace(
    start=1, 
    stop=10,
    num=4
)
a2

array([ 1.,  4.,  7., 10.])

In [10]:
np.random.randn(5)

array([ 1.05276945, -2.020489  ,  2.06713328, -0.61297326,  0.46679757])

In [12]:
np.random.randint(
    low=1,
    high=10,
    size=(3,3)
)

array([[1, 3, 9],
       [3, 5, 2],
       [4, 2, 5]])

In [21]:
np.random.randint(
    low=1,
    high=10,
    size=(5,3)
)

array([[6, 4, 4],
       [8, 8, 2],
       [8, 9, 6],
       [5, 3, 7],
       [2, 3, 9]])

In [25]:
np.ones(
    shape=(5,3),
    dtype=float,
)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [22]:
np.zeros(
    shape=(5,3),
    dtype=float,
)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [26]:
np.empty(
    shape=(5,3),
    dtype=float,
)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [27]:
np.eye(
    N=5, #number of rows,
    M=3, #number of columns,
    k=1, #index of digonal
)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [28]:
np.eye(
    N=5,
    M=3,
    k=-1
)

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [33]:
np.diag(
    v=[1,3,6,5],
    k=+1
)

array([[0, 1, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 6, 0],
       [0, 0, 0, 0, 5],
       [0, 0, 0, 0, 0]])

In [39]:
np.random.randn(5,3)

array([[-0.76394488, -1.14175409,  0.67342865],
       [-0.63964001, -1.10208884, -0.58952348],
       [-0.4798626 ,  0.83450386, -0.8424687 ],
       [ 1.91193919,  1.35709016,  1.4269995 ],
       [ 0.17735109, -1.05851997, -0.60697307]])

In [53]:
np.random.randint(
    low=2,
    high=20,
    size=(5,2,3,4), # 5 groups of 2 matricx having array of 3 rows and 4 columns
)

array([[[[14, 11,  9,  4],
         [ 5, 15,  6,  5],
         [17,  8, 14, 15]],

        [[14, 11, 14,  3],
         [14,  8,  4, 14],
         [12,  2, 18, 17]]],


       [[[17, 18,  9,  3],
         [ 6,  5,  4,  8],
         [ 3,  7, 11,  4]],

        [[13, 12,  4, 13],
         [12, 17,  5, 10],
         [ 5, 19, 16,  8]]],


       [[[ 6, 12, 10,  9],
         [15, 10,  2,  7],
         [ 9,  9, 19,  2]],

        [[ 5,  2, 14,  7],
         [10, 14,  2,  3],
         [ 7,  2, 15,  3]]],


       [[[ 8,  8, 13, 15],
         [12,  7, 14, 15],
         [ 7,  7, 19,  6]],

        [[14,  3,  4,  3],
         [ 2,  8, 14, 14],
         [12,  9, 16, 18]]],


       [[[13, 16, 16, 13],
         [ 5, 11, 11,  6],
         [15, 16, 18, 12]],

        [[12,  4,  8,  7],
         [13,  6, 15,  3],
         [ 3, 17, 12, 14]]]])

In [57]:
np.linspace(
    start=2,
    stop=20,
    num=6
).reshape(2,3)

array([[ 2. ,  5.6,  9.2],
       [12.8, 16.4, 20. ]])

In [58]:
np.array(
    object=[
        [1,2,3],
        [4,5,6]
    ]  
)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#np.diag() for digonal elements
#np.eye() identical metrix 
#np.ones() matrix with all value as one
#np.zeros() matrix with all value as zeroes 
#np.empty() matrxi with all values from the memory 
#np.ranom.randn() # all random float values 
#np.random.randint() #all the random intiger values
#np.arange() #when the distance between the values  is fixed 
#np.linspace() #when the number of the values are fixed 



In [52]:
np.arange(
    start=2, 
    stop=20,
    step=3
).reshape(2,3)

array([[ 2,  5,  8],
       [11, 14, 17]])

In [61]:
pd.Series(range(10))

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

In [62]:
pd.Series([1,2,3,4,5])

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [64]:
pd.Series(np.random.randn(5))

0   -1.853068
1   -2.986481
2   -0.177373
3    0.161344
4   -1.718829
dtype: float64

In [65]:
pd.Series(5, index=["a","b","c"])

a    5
b    5
c    5
dtype: int64

In [69]:
pd.DataFrame(
    data=pd.Series([1,2,3,4], index=["a","b,","c","d"], name="col_1")
)

col_1
a       1
b,      2
c       3
d       4

In [73]:
pd.DataFrame(
    data=np.random.randint(
        low=10,
        high=20,
        size=(5,4)
    ),
    columns=["col1","col2","col3","col4"]
)

col1  col2  col3  col4
0    11    19    18    12
1    10    16    12    15
2    13    19    16    19
3    12    12    19    17
4    18    17    13    14

In [78]:
pd.DataFrame(
    data={
        "col_1":np.random.randn(4),
        "col_2":list("abcd"),
        "col_3":np.array([1,2,3,4])
    }
)

col_1 col_2  col_3
0  0.570113     a      1
1  0.249047     b      2
2  1.205628     c      3
3 -0.875711     d      4

In [87]:
df=pd.DataFrame(
    data=np.random.randint(
        low=1,
        high=10,
        size=(3,3)
    ),
    columns=["col_1","col_2","col_3"]
)
df


col_1  col_2  col_3
0      5      4      7
1      9      1      7
2      1      7      4

In [88]:
df["col_3"] #series

0    7
1    7
2    4
Name: col_3, dtype: int32

In [89]:
df[["col_3"]] #df

col_3
0      7
1      7
2      4

In [93]:
df.iloc[:,1] #series

0    4
1    1
2    7
Name: col_2, dtype: int32

In [95]:
df.iloc[:,[1]] #df

col_2
0      4
1      1
2      7

In [97]:
df.iloc[:,[1,2]] #df

col_2  col_3
0      4      7
1      1      7
2      7      4

In [100]:
df.iloc[:,0:2] #df

col_1  col_2
0      5      4
1      9      1
2      1      7

In [101]:
df.iloc[:, [0,1]] #df

col_1  col_2
0      5      4
1      9      1
2      1      7

In [103]:
df.iloc[[0],[0,2]] #df 

col_1  col_3
0      5      7

In [105]:
df.iloc[[0],:] #df 

col_1  col_2  col_3
0      5      4      7

In [106]:
df.iloc[[0,1], [0,1]] #df

col_1  col_2
0      5      4
1      9      1

In [110]:
df.iloc[0:2,:] #df

col_1  col_2  col_3
0      5      4      7
1      9      1      7

In [111]:
df.iloc[1,:]# series

col_1    9
col_2    1
col_3    7
Name: 1, dtype: int32

In [112]:
df.loc[:,"col_1"] #series

0    5
1    9
2    1
Name: col_1, dtype: int32

In [117]:
df.loc[:,"col_1":"col_3"] #df

col_1  col_2  col_3
0      5      4      7
1      9      1      7
2      1      7      4

In [118]:
df.loc[:, ["col_1", "col_3"]] #df

col_1  col_3
0      5      7
1      9      7
2      1      4

In [119]:
df.loc[1:2,"col_2"] #series

1    1
2    7
Name: col_2, dtype: int32

In [124]:
df.loc[0:3, ["col_2", "col_3"]] #df

col_2  col_3
0      4      7
1      1      7
2      7      4

In [123]:
df.loc[[0,2], ["col_2"]] #df 

col_2
0      4
2      7

In [125]:
df[0:3]

col_1  col_2  col_3
0      5      4      7
1      9      1      7
2      1      7      4

In [130]:
df[0:2][["col_1"]]#df

col_1
0      5
1      9

In [136]:
df

col_1  col_2  col_3
0      5      4      7
1      9      1      7
2      1      7      4

In [137]:
df.insert(
    loc=1,
    column="new_col",
    value=[11,22,np.nan]
)

In [138]:
df

col_1  new_col  col_2  col_3
0      5     11.0      4      7
1      9     22.0      1      7
2      1      NaN      7      4

In [2]:
#numpy array:
import numpy as np
np.array([1,2,3,4,5]) #from a provided values list 

array([1, 2, 3, 4, 5])

In [5]:
np.random.randn(5) #generating random 5 values  

array([ 0.43071756, -0.22810848, -1.66082743, -0.56220476, -1.35958575])

In [13]:
np.ones((5,))# array of ones 

array([1., 1., 1., 1., 1.])

In [16]:
np.zeros((5,)) #array of zeros

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [18]:
np.arange(
    start=0,
    stop=13, 
    step=2
) # evenly distributed array # here we can control the distance between the points getting generated

array([ 0,  2,  4,  6,  8, 10, 12])

In [19]:
np.linspace(
    start=0, 
    stop=13, 
    num=5
) # generated 5 points , here we can control how many points should be generated within the limit

array([ 0.  ,  3.25,  6.5 ,  9.75, 13.  ])

In [25]:
np.empty(
    shape=(3,1)
) #creates the random array from the values in its memory

array([[ 8.96769526e-312],
       [ 8.96769526e-312],
       [-0.00000000e+000]])

In [37]:
np.eye(
    N=3, #number of rows 
    M=4, #number of columns
    k=1, # index of first column with one
    dtype=int,
    
) # identical matrix of 0 and 1

array([[0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [41]:
np.diag(
    v=[1,2,3,4], #diagonal elements
    k=1 #index of frist non zero value
)

array([[0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0]])

In [47]:
np.array(
    object=[
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ],
    dtype=float,
) #from nested list

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [48]:
np.random.randint(
    low=11,
    high=22,
    size=(3,3),
    
)

array([[11, 12, 12],
       [19, 12, 13],
       [14, 20, 18]])

In [60]:
np.random.randn(6).reshape(2,3)

array([[ 0.26700259,  0.16200856, -0.59013897],
       [-0.17241412, -0.94997069,  0.67566825]])

In [71]:
np.random.randint(
    low=0,
    high=20,
    size=(2,3)
)

array([[ 5, 17, 11],
       [ 8,  2,  2]])

In [56]:
np.arange(
    start=5,
    stop=16,
    step=2,
    dtype=float
).reshape(2,3)

array([[ 5.,  7.,  9.],
       [11., 13., 15.]])

In [62]:
np.arange(
    start=10, 
    stop =22, 
    step=3, 
    dtype=int
).reshape(2,2)

array([[10, 13],
       [16, 19]])

In [65]:
np.linspace(
    start=10, 
    stop=20,
    num=6,
    dtype=float
).reshape(2,3)

array([[10., 12., 14.],
       [16., 18., 20.]])

In [68]:
np.linspace(
    start=10,
    stop=20,
    num=6, 
    dtype=int
).reshape(2,3)

array([[10, 12, 14],
       [16, 18, 20]])

In [86]:
np.diag(
    v=[1,2,3,4],
    k=1,
)

array([[0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0]])

In [90]:
np.eye(
    N=3,
    M=4,
    k=1,
    dtype=int,
)

array([[0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [97]:
np.ones(
    shape=(2,3),
    dtype=int
)

array([[1, 1, 1],
       [1, 1, 1]])

In [95]:
np.zeros(
    shape=(2,3),
    dtype=int
)

array([[0, 0, 0],
       [0, 0, 0]])

In [98]:
import pandas as pd

In [100]:
pd.Series(
    data=[1,2,3,4], 
    index=["a", "b", "c", "d"]
)

a    1
b    2
c    3
d    4
dtype: int64

In [101]:
pd.Series(
    data=5, 
    index=["A","B", "C", "D"]
)

A    5
B    5
C    5
D    5
dtype: int64

In [105]:
pd.Series(
    data=range(5),
    dtype=float,
    name="Series 0 to 4"
)

0    0.0
1    1.0
2    2.0
3    3.0
4    4.0
Name: Series 0 to 4, dtype: float64

In [107]:
pd.Series(
    data=np.random.randn(5), 
    index=['a', 'b', 'c','d', 'e']
)

a   -0.128862
b    0.122139
c    0.714218
d   -0.677593
e   -1.713105
dtype: float64

In [126]:
pd.Series(
    data=np.random.randint(
        low=0, 
        high=16, 
        size=(4,1)
    ).flatten(),
    index=['a', 'b', 'c','d']
)

a     6
b    11
c     1
d     0
dtype: int32

In [120]:
pd.Series(
    data=np.arange(
        start=0,
        stop=16, 
        step=3, 
        dtype=float, 
    ), 
    index=['a', 'b', 'c','d','e','f']
)

a     0.0
b     3.0
c     6.0
d     9.0
e    12.0
f    15.0
dtype: float64

In [124]:
pd.Series(
    np.diag(
        v=[1,2,3]
    ).flatten()
)

0    1
1    0
2    0
3    0
4    2
5    0
6    0
7    0
8    3
dtype: int32

In [2]:
import pandas as pd

In [5]:
pd.DataFrame(
    data=[
        [1,2,3], 
        [4,5,6], 
        [7,8,9]
    ], 
    columns=['col_1', 'col_2', 'col_3']
)

col_1  col_2  col_3
0      1      2      3
1      4      5      6
2      7      8      9

In [7]:
pd.DataFrame(
    data=(
        (1,2,3), 
        (4,5,6), 
        (7,8,9)
    ), 
    columns=['col_1', 'col_2', 'col_3']
)

col_1  col_2  col_3
0      1      2      3
1      4      5      6
2      7      8      9

In [8]:
pd.DataFrame(
    data={
        'col_1':[1,2,3], 
        'col_2':[4,5,6],
        'col_3':[7,8,9]
    }
)

col_1  col_2  col_3
0      1      4      7
1      2      5      8
2      3      6      9

In [10]:
import numpy as np

In [12]:
pd.DataFrame(
    data=np.random.randn(9).reshape(3,3), 
    columns=['col_1', 'col_2', 'col_3']
)

col_1     col_2     col_3
0  0.122264  0.545533 -1.023557
1  0.189322  0.934867 -0.287072
2  1.325423  2.306104  1.375056

In [15]:
pd.DataFrame(
    data=np.random.randint(
        low=0, 
        high=20,
        size=(3,3)
    ),
    columns=['col_1', 'col_2','col_3']
)

col_1  col_2  col_3
0     19      0      7
1      8     11     13
2     16     14     11

In [19]:
pd.DataFrame(
    data={
        "col_1":np.linspace(
            start=10, 
            stop=20, 
            num=3, 
            dtype=float
        ),

        "col_2": pd.Series(
            data=['a','b', 'c']
        ), 

        "col_3": (1,2,3)
    }
)

col_1 col_2  col_3
0   10.0     a      1
1   15.0     b      2
2   20.0     c      3

In [34]:
df1=pd.DataFrame(
    data={
        "col_1":  pd.Series(
            data=np.arange(
                start=1, 
                stop=18,
                step=3,
                dtype=float
            )
        ),
        "col_2": np.eye(
            N=2, 
            M=3,
            k=1, 
            dtype=int
        ).flatten(),
        "col_3":('a', 'b','c','d', 'e', 'f')
    }
)

In [38]:
df1

col_1  col_2 col_3  col_4
0    1.0      0     a    2.0
1    4.0      1     b    8.0
2    7.0      0     c   14.0
3   10.0      0     d   20.0
4   13.0      0     e   26.0
5   16.0      1     f   32.0

In [37]:
df1['col_4']=df1['col_1']*2

In [40]:
df1=df1.assign(col_5=df1['col_4']*2)

In [3]:
import pandas as pd
import  numpy as np

In [4]:
np.zeros(
    shape=(3,3), 
    dtype=float, 
)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
np.ones(
    shape=(3,4),
    dtype=float
)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
np.eye(
    N=3, 
    M=4, 
    k=1, 
    dtype=int
)

array([[0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [9]:
np.diag(
    v=[1,2,3,2,4],
    k=1,
)

array([[0, 1, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0],
       [0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 2, 0],
       [0, 0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0, 0]])

In [13]:
np.random.randn(3,3)


array([[ 0.95159119, -0.25143224, -1.75674828],
       [ 0.19622024,  0.01011062, -0.81851925],
       [-0.8160123 , -0.32221424, -0.41904797]])

In [16]:
np.random.randint(
    low=3, 
    high=10,
    size=(3,3),
    dtype=int, 

)

array([[6, 8, 5],
       [5, 4, 8],
       [6, 9, 5]])

In [18]:
np.empty(
    shape=(3,3), 
    dtype=int
)

array([[         0,          0, -563548480],
       [       295, -563548544,        295],
       [-563550912,        295, -622881056]])

In [24]:
np.arange(
    start=5, 
    stop=16,
    step=2, 
).reshape(2,3)

array([[ 5,  7,  9],
       [11, 13, 15]])

In [27]:
np.linspace(
    start=10, 
    stop = 30, 
    num=12
).reshape(3,4)

array([[10.        , 11.81818182, 13.63636364, 15.45454545],
       [17.27272727, 19.09090909, 20.90909091, 22.72727273],
       [24.54545455, 26.36363636, 28.18181818, 30.        ]])

In [29]:
np.array([1,2,3,4,5,6]).reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
pd.Series([1,2,3,4,5,6])

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [31]:
pd.Series([1,2,3,4,5,6], index=["a", "b", "c", "d", "e", "f"])

a    1
b    2
c    3
d    4
e    5
f    6
dtype: int64

In [37]:
pd.Series(
    data=np.random.randn(2,2).flatten(), 
    index=['a', 'b', 'c', 'd']
)

a   -1.516635
b   -0.085494
c    0.579925
d    1.035235
dtype: float64

In [40]:
pd.Series(
    data=np.random.randint(
        low=10, 
        high=20,
        size=(2,2)
    ).flatten(), 
    index=['a', 'b', 'c','d']
)

a    14
b    18
c    12
d    17
dtype: int32

In [ ]:
pd.DataFrame(
    data={
        "one":
    }
)